// Regenerate typed ABI modules from the Foundry build artifacts.
//
// Reads contracts/out/<Contract>.sol/<Contract>.json and emits
// packages/sdk/src/abis/<contract>.ts with the ABI as a viem-friendly
// `as const` literal. Run after `forge build`:
//
//   pnpm --filter @noviq/sdk gen:abis
//
// Keeping this a generator (not hand-maintained files) means the SDK bindings
// can never silently drift from the deployed bytecode.

import { mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const here = dirname(fileURLToPath(import.meta.url))
const outDir = resolve(here, "../../../contracts/out")
const abiDir = resolve(here, "../src/abis")

// contract file name (without .sol) → exported const name
const CONTRACTS = {
  PolicyGuard: "policyGuardAbi",
  CovenantAccount: "covenantAccountAbi",
  CovenantAccountFactory: "covenantAccountFactoryAbi",
  AgentBond: "agentBondAbi",
}

mkdirSync(abiDir, { recursive: true })

const indexLines = ["// AUTO-GENERATED by scripts/generate-abis.mjs — do not edit by hand.", ""]

for (const [contract, exportName] of Object.entries(CONTRACTS)) {
  const artifactPath = resolve(outDir, `${contract}.sol/${contract}.json`)
  const artifact = JSON.parse(readFileSync(artifactPath, "utf8"))
  const abi = artifact.abi

  const fileName = `${contract[0].toLowerCase()}${contract.slice(1)}`
  const body = [
    `// AUTO-GENERATED from contracts/out/${contract}.sol/${contract}.json — do not edit by hand.`,
    `export const ${exportName} = ${JSON.stringify(abi, null, 2)} as const`,
    "",
  ].join("\n")

  writeFileSync(resolve(abiDir, `${fileName}.ts`), body)
  indexLines.push(`export { ${exportName} } from "./${fileName}"`)
  console.log(`wrote abis/${fileName}.ts (${abi.length} entries)`)
}

indexLines.push("")
writeFileSync(resolve(abiDir, "index.ts"), indexLines.join("\n"))
console.log("wrote abis/index.ts")
